### ISSUE TITLE
HW 3

### ISSUE THREAD

**Issue by pdirmeyer** [areed29/CLIM680_Fall2021#4]
Largely good Austin - but there are a number of details that need to be addressed:

1. You extract `precip` from ERA5 for the months that overlap the NAO index data array, but then you calculate anomalies on the entire ERA5 dataset - it would be much more efficient to restrict this calculation only to `precip`. Likewise for the composites - your print statements show that you are processing the entire `xarray.dataset` and not just the data array for precipitation.  You could also use the `.load()` method to speed up your calculations from data read from files by storing results (e.g., your composites) in memory.
2. `ds_anoms` has 504 time steps.  What's the sum of the counts for your positive, negative and neutral NAO? Why don't they match?  Similarly, the weighted-by-count averages of your 3 composite anomalies don't add up to zero. There are two separate reasons contributing to this - see if you can figure it out.
3. The ERA5 precip data have units of "m" (a total, not a rate) and are monthly, but you label it "m/day". I think it is really "m/month" - you could multiply by 1000 to get the more usual "mm/month". 
4. Your color scale does not resolve the range of the data - only two colors are shown. Try a better set of `clevs`.
5. You should choose your contour intervals so the color changes in the middle at 0.0.

**Comment by areed29** [comment]
Thanks for the suggestions! I have committed more changes to the assignment
For #1- that is true; I changed the anomaly calculations to only be done for the precip array.
For #2- Also a good point I did not catch- I saw my first mistake; simply not including values equal to 1 or -1 for one of the metrics (I now included them in pos/neg NAO). The total of the counts now amount to 501, still not 504, so that must get into the second reason contributing to this. It hasn't occurred to me yet so I'll keep thinking.
For #3- Another good point; for the documentation for ERA5 I'm using for total precipitation: " ...For the monthly averaged reanalysis and the monthly averaged ensemble members, the accumulation period is 1 day. For the monthly averaged reanalysis by hour of day, the accumulation period is 1 hour and for the monthly averaged ensemble members by hour of day, the accumulation period is 3 hours. The units of this parameter are depth in metres of water equivalent."
-This indicates that it is monthly averages of daily data. Since it is grouped by month and averaged over months, it might still be best to include meters/month as you mentioned...
#4,5 should now be resolved

**Comment by pdirmeyer** [comment]
On #2, have a look at the NAO time series - the last 3 months are missing (nan).

**Comment by areed29** [comment]
FYI; The latest changes to assignment #3 are now on Github!

**Comment by pdirmeyer** [comment]
Looks good!
